# Generated by Django 4.2.3 on 2024-02-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_reason',
            name='stock_adjustment',
        ),
    ]
