# Generated by Django 4.2.3 on 2024-02-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0034_stock_adjustment_stock_adjustment_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_adjustment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
