# Generated by Django 4.2.3 on 2024-02-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0035_stock_adjustment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_adjustment_items',
            name='type',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
