# Generated by Django 4.2.3 on 2024-02-15 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0037_stock_adjustment_comment_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_adjustment',
            name='comment',
        ),
        migrations.CreateModel(
            name='Stock_Adjustment_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='', max_length=500)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('login_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('stock_adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.stock_adjustment')),
                ('stock_adjustmentitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.stock_adjustment_items')),
            ],
        ),
    ]
